version: '3.9'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0
    restart: always
    command: start-dev
    ports:
      - "8888:8080"
    env_file:
      - .env.keycloak
    networks:
      - chatybe 
  db:
    container_name: dbchaty
    image: postgres
    restart: always
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=chatypwd
      - POSTGRES_USER=chaty
      - POSTGRES_DB=chaty
    networks:
      - chatybe
networks:
  chatybe:
